### ISSUE TITLE
Hashes not working for certain types?

### ISSUE THREAD

**Issue by mthom** [deech/shen-elisp#7]
Hey deech,

It seems that shen-elisp has some trouble hashing certain types. I've got the following Shen code, which compiles without issue in shen-elisp (sorry for the poor formatting):

(define string-concat
  { (list string) --> string }
  []  -> ""
  [S] -> S
  [S | Ss] -> (@s S " " (string-concat Ss)))

(datatype verified-types-for-lists
  ________________________________________
  (empty? Xs) : verified >> Xs : (list A);

  _______________________________________
  (cons? Xs) : verified >> Xs : (list A);)

(define ->str
  { A --> string }
  Xs  -> "()" where (empty? Xs)
  Xs  -> (@s "(" (string-concat (map ->str Xs)) ")") where (cons? Xs)
  Str -> (str Str))

(datatype type-reps  
  ______________________________________________
  X : (type-rep A) >> (get X type-rep) : string;    

  let Tag (put (eval X) type-rep (->str A))
  _________________________________________
  (tag-value-with-rep X A);
  
  X : A; (tag-value-with-rep X A);
  _______________________________
  X : (type-rep A);)

(define type-of
  { (type-rep A) --> string }
  X -> (get X type-rep))

and here's it behavior on some inputs:

(28+) (type-of 1)
"number" : string

(29+) (type-of [1 2 3])
"(list number)" : string

(30+) (type-of "string")
"string" : string

(31+) (type-of true)
"boolean" : string

(32+) (type-of (@p 1 2))

pointer not found: #s(hash-table size 3 test eql rehash-size 3.0 rehash-threshold 0.8 data (0 shen.tuple 1 1 2 2))

(33+) (type-of (@v 1 2 3 <>))

pointer not found: #s(hash-table size 4 test eql rehash-size 3.0 rehash-threshold 0.8 data (0 3 1 1 2 2 3 3))

Lines 28 - 31 behave as expected, but 32 and 33 do not.

**Comment by deech** [comment]
I was having a little trouble with the formatting so I made a gist: https://gist.github.com/deech/95a6211fb51bb473059255879f4a6f03. Is it right?

**Comment by mthom** [comment]
No problem. Line 28 of the gist should be removed, but everything else is correct.

**Comment by deech** [comment]
This should be fixed now. Could you test and close if it is? Thanks!

**Comment by mthom** [comment]
I've updated shen-elisp through quelpa, and I'm still getting some strange errors:

(20+) (type-of (@p 3 3))
(wrong-type-argument symbolp #[0 \305\300\301\304\302\303%\207 [(tag-value-with-rep (@p 3 3) #s(hash-table size 2 test eql rehash-size 3.0 rehash-threshold 0.8 data (0 shen.pvar 1 7))) nil 1 #[0 \302\301\300\303#\207 [1 #s(hash-table size 2 test eql rehash-size 3.0 rehash-threshold 0.8 data (0 shen.pvar 1 2)) shen/return shen.void] 4 

(fn)] #s(hash-table size 2 test eql rehash-size 3.0 rehash-threshold 0.8 data (0 shen.pvar 1 18)) shen/shen.udefs*] 6 

(fn)])

**Comment by deech** [comment]
Just did it. Works for fine for me. Try installing on a fresh Emacs and seeing it's still occurring. Might be some stale state in the image.

**Comment by mthom** [comment]
It is still occurring, I'm afraid. I'm updating shen-elisp using the quelpa code in the readme, emacs version is 24.5.1.

**Comment by deech** [comment]
Here's a screenshot of my interaction. On the right is my version of your code, on the left is the REPL. Do you have something different on your end?

![type-rep-local](https://cloud.githubusercontent.com/assets/76703/15810263/5e3a21a8-2b62-11e6-8477-824ff2a51963.png)

**Comment by mthom** [comment]
No, the code in the right pane is exactly what I have. The port version on my end is also 1.7.

**Comment by deech** [comment]
I just upped the Emacs version to `24.4`. Any chance that made a difference? If not would you mind trying it in a fresh Emacs instance? I sometimes see errors like the above when I've changed `shen-elisp` but haven't deleted and re-started the REPL. If none of those work I'm tapped on ideas. It seems like we're running in the same environment.

**Comment by mthom** [comment]
Cool, that did it. Closing the issue.
